language: c
dist: xenial
addons:
    apt:
        packages:
            - qemu-system-x86
            - libseccomp-dev
script: ./configure.sh && make && tests/run-tests.sh
matrix:
  include:
    - os: linux
    - env: CC=gcc-7
      os: linux-ppc64le
      dist: bionic
      sudo: required
      before_script: 
        - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        - sudo apt-get -y update
        - sudo apt-get -y install gcc-7
